exports.userList=[
    {
        id:1,
        name:"abir",
        age:25,
        isWorking:false
    },
    {
        id:2,
        name:"maher",
        age:29,
        isWorking:false
    },
    {
        id:3,
        name:"nour",
        age:23,
        isWorking:false
    },
    {
        id:4,
        name:"marwen",
        age:32,
        isWorking:true
    },
    {
        id:5,
        name:"ramzi",
        age:30,
        isWorking:true
    }
]